/**
 * Telegram animatsion emoji xaritasining qo'shimcha qismi:
 * Animals and Nature, Food and Drink, Activity, Travel and Places.
 *
 * Fayl nomlari `Tarikul-Islam-Anik/Telegram-Animated-Emojis` repozitoriysidagi
 * haqiqiy Telegram to'plamidan olingan (faqat mavjudligi tekshirilganlari).
 */
export const EXTRA_TELEGRAM_EMOJI_PATHS: Record<string, string> = {
  // ------------------------ Animals and Nature ------------------------
  '\u{1F436}': 'Animals and Nature/Dog Face',
  '\u{1F431}': 'Animals and Nature/Cat Face',
  '\u{1F42D}': 'Animals and Nature/Mouse Face',
  '\u{1F439}': 'Animals and Nature/Hamster',
  '\u{1F430}': 'Animals and Nature/Rabbit Face',
  '\u{1F98A}': 'Animals and Nature/Fox',
  '\u{1F43B}': 'Animals and Nature/Bear',
  '\u{1F43C}': 'Animals and Nature/Panda',
  '\u{1F428}': 'Animals and Nature/Koala',
  '\u{1F42F}': 'Animals and Nature/Tiger Face',
  '\u{1F981}': 'Animals and Nature/Lion',
  '\u{1F42E}': 'Animals and Nature/Cow',
  '\u{1F437}': 'Animals and Nature/Pig Face',
  '\u{1F43D}': 'Animals and Nature/Pig Nose',
  '\u{1F438}': 'Animals and Nature/Frog',
  '\u{1F435}': 'Animals and Nature/Monkey Face',
  '\u{1F414}': 'Animals and Nature/Chicken',
  '\u{1F427}': 'Animals and Nature/Penguin',
  '\u{1F426}': 'Animals and Nature/Bird',
  '\u{1F424}': 'Animals and Nature/Baby Chick',
  '\u{1F423}': 'Animals and Nature/Hatching Chick',
  '\u{1F425}': 'Animals and Nature/Front Facing Baby Chick',
  '\u{1F986}': 'Animals and Nature/Duck',
  '\u{1F989}': 'Animals and Nature/Owl',
  '\u{1F987}': 'Animals and Nature/Bat',
  '\u{1F434}': 'Animals and Nature/Horse Face',
  '\u{1F40E}': 'Animals and Nature/Horse',
  '\u{1F984}': 'Animals and Nature/Unicorn',
  '\u{1F41D}': 'Animals and Nature/Honeybee',
  '\u{1F41B}': 'Animals and Nature/Bug',
  '\u{1F98B}': 'Animals and Nature/Butterfly',
  '\u{1F40C}': 'Animals and Nature/Snail',
  '\u{1F41E}': 'Animals and Nature/Lady Beetle',
  '\u{1F41C}': 'Animals and Nature/Ant',
  '\u{1FAB2}': 'Animals and Nature/Beetle',
  '\u{1FAB3}': 'Animals and Nature/Cockroach',
  '\u{1F997}': 'Animals and Nature/Cricket',
  '\u{1F99F}': 'Animals and Nature/Mosquito',
  '\u{1F577}': 'Animals and Nature/Spider',
  '\u{1F578}': 'Animals and Nature/Spider Web',
  '\u{1F422}': 'Animals and Nature/Turtle',
  '\u{1F40D}': 'Animals and Nature/Snake',
  '\u{1F996}': 'Animals and Nature/T Rex',
  '\u{1F995}': 'Animals and Nature/Sauropod',
  '\u{1F419}': 'Animals and Nature/Octopus',
  '\u{1F991}': 'Animals and Nature/Squid',
  '\u{1F990}': 'Animals and Nature/Shrimp',
  '\u{1F99E}': 'Animals and Nature/Lobster',
  '\u{1F41F}': 'Animals and Nature/Fish',
  '\u{1F420}': 'Animals and Nature/Tropical Fish',
  '\u{1F433}': 'Animals and Nature/Spouting Whale',
  '\u{1F9AD}': 'Animals and Nature/Seal',
  '\u{1F993}': 'Animals and Nature/Zebra',
  '\u{1F992}': 'Animals and Nature/Giraffe',
  '\u{1F98C}': 'Animals and Nature/Deer',
  '\u{1F408}': 'Animals and Nature/Cat',
  '\u{1F407}': 'Animals and Nature/Rabbit',
  '\u{1F99D}': 'Animals and Nature/Raccoon',
  '\u{1F994}': 'Animals and Nature/Hedgehog',
  '\u{1F9A9}': 'Animals and Nature/Flamingo',
  '\u{1F99C}': 'Animals and Nature/Parrot',
  '\u{1F9A2}': 'Animals and Nature/Swan',
  '\u{1F54A}': 'Animals and Nature/Dove',
  '\u{1F98D}': 'Animals and Nature/Gorilla',
  '\u{1F998}': 'Animals and Nature/Kangaroo',
  '\u{1F999}': 'Animals and Nature/Llama',
  '\u{1F402}': 'Animals and Nature/Ox',
  '\u{1F43E}': 'Animals and Nature/Paw Prints',
  '\u{1F9A0}': 'Animals and Nature/Microbe',
  '\u{1F338}': 'Animals and Nature/Cherry Blossom',
  '\u{1F3F5}': 'Animals and Nature/Rosette',
  '\u{1F339}': 'Animals and Nature/Rose',
  '\u{1F33A}': 'Animals and Nature/Hibiscus',
  '\u{1F33C}': 'Animals and Nature/Blossom',
  '\u{1F337}': 'Animals and Nature/Tulip',
  '\u{1F490}': 'Animals and Nature/Bouquet',
  '\u{1F331}': 'Animals and Nature/Seedling',
  '\u{1F332}': 'Animals and Nature/Evergreen Tree',
  '\u{1F333}': 'Animals and Nature/Deciduous Tree',
  '\u{1F334}': 'Animals and Nature/Palm Tree',
  '\u{1F335}': 'Animals and Nature/Cactus',
  '\u{1F33F}': 'Animals and Nature/Herb',
  '\u{2618}': 'Animals and Nature/Shamrock',
  '\u{1F340}': 'Animals and Nature/Four Leaf Clover',
  '\u{1F525}': 'Animals and Nature/Fire',
  '\u{2B50}': 'Animals and Nature/Star',
  '\u{1F31F}': 'Animals and Nature/Glowing Star',
  '\u{26A1}': 'Animals and Nature/High Voltage',
  '\u{1F308}': 'Animals and Nature/Rainbow',
  '\u{2601}': 'Animals and Nature/Cloud',
  '\u{26C5}': 'Animals and Nature/Sun Behind Cloud',
  '\u{1F324}': 'Animals and Nature/Sun Behind Small Cloud',
  '\u{1F325}': 'Animals and Nature/Sun Behind Large Cloud',
  '\u{1F326}': 'Animals and Nature/Sun Behind Rain Cloud',
  '\u{1F327}': 'Animals and Nature/Cloud With Rain',
  '\u{1F328}': 'Animals and Nature/Cloud With Snow',
  '\u{1F329}': 'Animals and Nature/Cloud With Lightning',
  '\u{26C8}': 'Animals and Nature/Cloud With Lightning And Rain',
  '\u{2600}': 'Animals and Nature/Sun',
  '\u{1F31E}': 'Animals and Nature/Sun With Face',
  '\u{1F31D}': 'Animals and Nature/Full Moon Face',
  '\u{1F31A}': 'Animals and Nature/New Moon Face',
  '\u{1F31B}': 'Animals and Nature/First Quarter Moon Face',
  '\u{1F31C}': 'Animals and Nature/Last Quarter Moon Face',
  '\u{1F315}': 'Animals and Nature/Full Moon',
  '\u{1F311}': 'Animals and Nature/New Moon',
  '\u{1F313}': 'Animals and Nature/First Quarter Moon',
  '\u{1F317}': 'Animals and Nature/Last Quarter Moon',
  '\u{1F318}': 'Animals and Nature/Waning Crescent Moon',
  '\u{1F312}': 'Animals and Nature/Waxing Crescent Moon',
  '\u{1F314}': 'Animals and Nature/Waxing Gibbous Moon',
  '\u{2744}': 'Animals and Nature/Snowflake',
  '\u{2603}': 'Animals and Nature/Snowman',
  '\u{26C4}': 'Animals and Nature/Snowman Without Snow',

  // -------------------------- Food and Drink --------------------------
  '\u{1F34C}': 'Food and Drink/Banana',
  '\u{1F353}': 'Food and Drink/Strawberry',
  '\u{1F355}': 'Food and Drink/Pizza',
  '\u{1F354}': 'Food and Drink/Hamburger',
  '\u{1F35F}': 'Food and Drink/French Fries',
  '\u{1F32D}': 'Food and Drink/Hot Dog',
  '\u{1F96A}': 'Food and Drink/Sandwich',
  '\u{1F959}': 'Food and Drink/Stuffed Flatbread',
  '\u{1F32E}': 'Food and Drink/Taco',
  '\u{1F37F}': 'Food and Drink/Popcorn',
  '\u{1F369}': 'Food and Drink/Doughnut',
  '\u{1F36A}': 'Food and Drink/Cookie',
  '\u{1F382}': 'Food and Drink/Birthday Cake',
  '\u{1F370}': 'Food and Drink/Shortcake',
  '\u{1F9C1}': 'Food and Drink/Cupcake',
  '\u{1F36B}': 'Food and Drink/Chocolate Bar',
  '\u{1F36D}': 'Food and Drink/Lollipop',
  '\u{1F366}': 'Food and Drink/Soft Ice Cream',
  '\u{1F36E}': 'Food and Drink/Custard',
  '\u{1F95E}': 'Food and Drink/Pancakes',
  '\u{1F968}': 'Food and Drink/Pretzel',
  '\u{1F363}': 'Food and Drink/Sushi',
  '\u{1F371}': 'Food and Drink/Bento Box',
  '\u{1F359}': 'Food and Drink/Rice Ball',
  '\u{1F358}': 'Food and Drink/Rice Cracker',
  '\u{1F362}': 'Food and Drink/Oden',
  '\u{1F361}': 'Food and Drink/Dango',
  '\u{1F365}': 'Food and Drink/Fish Cake With Swirl',
  '\u{1F356}': 'Food and Drink/Meat On Bone',
  '\u{1F357}': 'Food and Drink/Poultry Leg',
  '\u{1F96B}': 'Food and Drink/Canned Food',
  '\u{1F373}': 'Food and Drink/Cooking',
  '\u{1F967}': 'Food and Drink/Pie',
  '\u{1F37D}': 'Food and Drink/Fork And Knife With Plate',
  '\u{2615}': 'Food and Drink/Hot Beverage',
  '\u{1F9CB}': 'Food and Drink/Bubble Tea',
  '\u{1F964}': 'Food and Drink/Cup With Straw',
  '\u{1F95B}': 'Food and Drink/Glass Of Milk',
  '\u{1F377}': 'Food and Drink/Wine Glass',
  '\u{1F378}': 'Food and Drink/Cocktail Glass',
  '\u{1F379}': 'Food and Drink/Tropical Drink',
  '\u{1F942}': 'Food and Drink/Clinking Glasses',
  '\u{1F37E}': 'Food and Drink/Bottle With Popping Cork',
  '\u{1F943}': 'Food and Drink/Tumbler Glass',
  '\u{1F37C}': 'Food and Drink/Baby Bottle',
  '\u{1F9C9}': 'Food and Drink/Mate',
  '\u{1F9C3}': 'Food and Drink/Beverage Box',
  '\u{1FAD7}': 'Food and Drink/Pouring Liquid',

  // ----------------------------- Activity -----------------------------
  '\u{26BD}': 'Activity/Soccer Ball',
  '\u{1F3C0}': 'Activity/Basketball',
  '\u{1F3C6}': 'Activity/Trophy',
  '\u{1F947}': 'Activity/1st Place Medal',
  '\u{1F948}': 'Activity/2nd Place Medal',
  '\u{1F949}': 'Activity/3rd Place Medal',
  '\u{1F3C5}': 'Activity/Sports Medal',
  '\u{1F396}': 'Activity/Military Medal',
  '\u{1F389}': 'Activity/Party Popper',
  '\u{1F38A}': 'Activity/Confetti Ball',
  '\u{1F388}': 'Activity/Balloon',
  '\u{1F386}': 'Activity/Fireworks',
  '\u{1F387}': 'Activity/Sparkler',
  '\u{1F9E8}': 'Activity/Firecracker',
  '\u{2728}': 'Activity/Sparkles',
  '\u{1F383}': 'Activity/Jack O Lantern',
  '\u{1F384}': 'Activity/Christmas Tree',
  '\u{1F3A8}': 'Activity/Artist Palette',
  '\u{1F3AD}': 'Activity/Performing Arts',
  '\u{1F3AE}': 'Activity/Video Game',
  '\u{1F3AB}': 'Activity/Ticket',
  '\u{1F39F}': 'Activity/Admission Tickets',
  '\u{1F52E}': 'Activity/Crystal Ball',
  '\u{1FA84}': 'Activity/Magic Wand',
  '\u{1FAA9}': 'Activity/Mirror Ball',

  // ------------------------ Travel and Places -------------------------
  '\u{2708}': 'Travel and Places/Airplane',
  '\u{1F680}': 'Travel and Places/Rocket',
  '\u{1F697}': 'Travel and Places/Automobile',
  '\u{1F695}': 'Travel and Places/Taxi',
  '\u{1F691}': 'Travel and Places/Ambulance',
  '\u{1F693}': 'Travel and Places/Police Car',
  '\u{1F682}': 'Travel and Places/Locomotive',
  '\u{1F6E5}': 'Travel and Places/Motor Boat',
  '\u{1F3E0}': 'Travel and Places/House',
  '\u{1F3D6}': 'Travel and Places/Beach With Umbrella',
  '\u{1F3DD}': 'Travel and Places/Desert Island',
  '\u{1F3D5}': 'Travel and Places/Camping',
  '\u{1F3A2}': 'Travel and Places/Roller Coaster',
  '\u{2668}': 'Travel and Places/Hot Springs',
  '\u{1F5FF}': 'Travel and Places/Moai',
  '\u{1F3DB}': 'Travel and Places/Classical Building',
  '\u{1F9ED}': 'Travel and Places/Compass',
};
