export type InternationalServiceLevel = 'economy' | 'standard' | 'express';
export type InternationalIncoterm = 'DAP' | 'DDP';
export type LogisticsTransportMode = 'courier' | 'road' | 'air' | 'sea' | 'rail' | 'multimodal' | 'pickup';

export interface InternationalShippingQuote {
  quote_id: string;
  origin_country_code: string;
  destination_country_code: string;
  international: boolean;
  service_level: InternationalServiceLevel;
  incoterm: InternationalIncoterm;
  transport_mode: LogisticsTransportMode;
  currency: string;
  cart_value: number;
  billable_weight_kg: number;
  shipping_charge: number;
  estimated_duty: number;
  estimated_vat: number;
  customs_handling: number;
  estimated_import_charges: number;
  checkout_total: number;
  estimated_landed_total: number;
  eta_days_min: number;
  eta_days_max: number;
  estimate_only: boolean;
  customs_collected_at_checkout: boolean;
  metadata_complete: boolean;
  warnings: string[];
  expires_at?: string;
  rate_source?: string;
}

export const INTERNATIONAL_SERVICE_OPTIONS: Array<{
  id: InternationalServiceLevel;
  label: string;
  subtitle: string;
}> = [
  { id: 'economy', label: 'Economy', subtitle: 'Arzonroq · multimodal / avto / dengiz' },
  { id: 'standard', label: 'Standard', subtitle: 'Muvozanatli · avia yoki multimodal' },
  { id: 'express', label: 'Express', subtitle: 'Eng tez · avia, mos yuklar uchun' },
];

// ISO 3166-1 alpha-2 codes. Labels are generated by Intl.DisplayNames so the
// selector remains global without shipping a second hand-maintained country-name table.
export const ISO_COUNTRY_CODES = [
  'AD','AE','AF','AG','AI','AL','AM','AO','AQ','AR','AS','AT','AU','AW','AX','AZ',
  'BA','BB','BD','BE','BF','BG','BH','BI','BJ','BL','BM','BN','BO','BQ','BR','BS','BT','BV','BW','BY','BZ',
  'CA','CC','CD','CF','CG','CH','CI','CK','CL','CM','CN','CO','CR','CU','CV','CW','CX','CY','CZ',
  'DE','DJ','DK','DM','DO','DZ','EC','EE','EG','EH','ER','ES','ET','FI','FJ','FK','FM','FO','FR',
  'GA','GB','GD','GE','GF','GG','GH','GI','GL','GM','GN','GP','GQ','GR','GS','GT','GU','GW','GY',
  'HK','HM','HN','HR','HT','HU','ID','IE','IL','IM','IN','IO','IQ','IR','IS','IT','JE','JM','JO','JP',
  'KE','KG','KH','KI','KM','KN','KP','KR','KW','KY','KZ','LA','LB','LC','LI','LK','LR','LS','LT','LU','LV','LY',
  'MA','MC','MD','ME','MF','MG','MH','MK','ML','MM','MN','MO','MP','MQ','MR','MS','MT','MU','MV','MW','MX','MY','MZ',
  'NA','NC','NE','NF','NG','NI','NL','NO','NP','NR','NU','NZ','OM','PA','PE','PF','PG','PH','PK','PL','PM','PN','PR','PS','PT','PW','PY',
  'QA','RE','RO','RS','RU','RW','SA','SB','SC','SD','SE','SG','SH','SI','SJ','SK','SL','SM','SN','SO','SR','SS','ST','SV','SX','SY','SZ',
  'TC','TD','TF','TG','TH','TJ','TK','TL','TM','TN','TO','TR','TT','TV','TW','TZ','UA','UG','UM','US','UY','UZ',
  'VA','VC','VE','VG','VI','VN','VU','WF','WS','YE','YT','ZA','ZM','ZW',
] as const;

let displayNames: Intl.DisplayNames | null | undefined;

export function countryLabel(code: string) {
  try {
    if (displayNames === undefined) {
      displayNames = typeof Intl !== 'undefined' && 'DisplayNames' in Intl
        ? new Intl.DisplayNames(['uz', 'en'], { type: 'region' })
        : null;
    }
    return displayNames?.of(code) || code;
  } catch {
    return code;
  }
}

export const INTERNATIONAL_COUNTRY_OPTIONS = ISO_COUNTRY_CODES
  .map(code => ({ code, label: countryLabel(code) }))
  .sort((a, b) => a.label.localeCompare(b.label, 'uz'));

export function transportModeLabel(mode?: string | null) {
  const labels: Record<string, string> = {
    courier: 'Kuryer',
    road: 'Avtomobil',
    air: 'Avia',
    sea: 'Dengiz',
    rail: 'Temir yo‘l',
    multimodal: 'Multimodal',
    pickup: 'Olib ketish',
  };
  return labels[String(mode || '').toLowerCase()] || mode || '—';
}

export function serviceLevelLabel(level?: string | null) {
  return INTERNATIONAL_SERVICE_OPTIONS.find(item => item.id === level)?.label || level || '—';
}

export function etaLabel(quote?: Pick<InternationalShippingQuote, 'eta_days_min' | 'eta_days_max'> | null) {
  if (!quote) return '—';
  if (quote.eta_days_min === quote.eta_days_max) return `${quote.eta_days_min} kun`;
  return `${quote.eta_days_min}–${quote.eta_days_max} kun`;
}

export function normalizeInternationalQuote(value: unknown): InternationalShippingQuote | null {
  if (!value || typeof value !== 'object') return null;
  const q = value as Record<string, unknown>;
  if (!q.quote_id || !q.destination_country_code) return null;
  const num = (key: string) => Number(q[key] ?? 0);
  return {
    quote_id: String(q.quote_id),
    origin_country_code: String(q.origin_country_code || ''),
    destination_country_code: String(q.destination_country_code || ''),
    international: Boolean(q.international),
    service_level: String(q.service_level || 'standard') as InternationalServiceLevel,
    incoterm: String(q.incoterm || 'DAP') as InternationalIncoterm,
    transport_mode: String(q.transport_mode || 'multimodal') as LogisticsTransportMode,
    currency: String(q.currency || 'USD'),
    cart_value: num('cart_value'),
    billable_weight_kg: num('billable_weight_kg'),
    shipping_charge: num('shipping_charge'),
    estimated_duty: num('estimated_duty'),
    estimated_vat: num('estimated_vat'),
    customs_handling: num('customs_handling'),
    estimated_import_charges: num('estimated_import_charges'),
    checkout_total: num('checkout_total'),
    estimated_landed_total: num('estimated_landed_total'),
    eta_days_min: num('eta_days_min'),
    eta_days_max: num('eta_days_max'),
    estimate_only: Boolean(q.estimate_only),
    customs_collected_at_checkout: Boolean(q.customs_collected_at_checkout),
    metadata_complete: Boolean(q.metadata_complete),
    warnings: Array.isArray(q.warnings) ? q.warnings.map(String) : [],
    expires_at: q.expires_at ? String(q.expires_at) : undefined,
    rate_source: q.rate_source ? String(q.rate_source) : undefined,
  };
}
