-- Durable Alsamos AI agent runs.
-- Long tasks are checkpointed here so Edge Function workers can continue in
-- bounded chunks even when the browser disconnects or an isolate is recycled.

create table if not exists public.ai_agent_runs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  conversation_id uuid null references public.ai_conversations(id) on delete set null,
  mode text not null default 'agent' check (mode in ('chat', 'agent')),
  requested_model text not null default 'auto',
  resolved_model text null,
  language text null,
  task text null,
  tool_groups text[] not null default '{}',
  status text not null default 'queued' check (
    status in ('queued', 'running', 'completed', 'failed', 'cancelled', 'awaiting_continue')
  ),
  input jsonb not null default '{}'::jsonb,
  checkpoint jsonb not null default '{}'::jsonb,
  round_count integer not null default 0 check (round_count >= 0),
  tool_call_count integer not null default 0 check (tool_call_count >= 0),
  max_rounds integer not null default 12 check (max_rounds between 1 and 96),
  max_tool_calls integer not null default 24 check (max_tool_calls between 1 and 256),
  max_run_ms integer not null default 1800000 check (max_run_ms between 30000 and 3600000),
  dispatch_token text not null,
  lease_until timestamptz null,
  last_error text null,
  final_text text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz null
);

create index if not exists ai_agent_runs_user_updated_idx
  on public.ai_agent_runs(user_id, updated_at desc);
create index if not exists ai_agent_runs_status_updated_idx
  on public.ai_agent_runs(status, updated_at);
create index if not exists ai_agent_runs_conversation_idx
  on public.ai_agent_runs(conversation_id, created_at desc)
  where conversation_id is not null;

create table if not exists public.ai_agent_run_events (
  id bigint generated by default as identity primary key,
  run_id uuid not null references public.ai_agent_runs(id) on delete cascade,
  type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists ai_agent_run_events_run_id_id_idx
  on public.ai_agent_run_events(run_id, id);

alter table public.ai_agent_runs enable row level security;
alter table public.ai_agent_run_events enable row level security;

-- Users can inspect only their own durable run state. Mutations remain server-side.
drop policy if exists "Users can read own AI agent runs" on public.ai_agent_runs;
create policy "Users can read own AI agent runs"
  on public.ai_agent_runs for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Users can read own AI agent run events" on public.ai_agent_run_events;
create policy "Users can read own AI agent run events"
  on public.ai_agent_run_events for select
  to authenticated
  using (
    exists (
      select 1 from public.ai_agent_runs r
      where r.id = ai_agent_run_events.run_id
        and r.user_id = auth.uid()
    )
  );

revoke all on public.ai_agent_runs from anon, authenticated;
revoke all on public.ai_agent_run_events from anon, authenticated;
grant select on public.ai_agent_runs to authenticated;
grant select on public.ai_agent_run_events to authenticated;

grant select, insert, update, delete on public.ai_agent_runs to service_role;
grant select, insert, update, delete on public.ai_agent_run_events to service_role;
grant usage, select on sequence public.ai_agent_run_events_id_seq to service_role;
