-- =============================================================================
-- Alsamos first-party Global Search
-- Own crawl/index/search stack. No Google/Bing/Yandex/Brave search APIs.
-- =============================================================================

create extension if not exists pg_trgm;

create table if not exists public.web_search_documents (
  id uuid primary key default gen_random_uuid(),
  url text not null unique,
  canonical_url text,
  domain text not null,
  path text not null default '/',
  title text not null default '',
  description text not null default '',
  content_text text not null default '',
  language text,
  kind text not null default 'web'
    check (kind in ('web', 'wikipedia', 'news', 'image', 'video')),
  content_type text,
  thumbnail_url text,
  author text,
  published_at timestamptz,
  width integer,
  height integer,
  duration_seconds integer,
  status_code integer,
  content_hash text,
  crawl_depth integer not null default 0,
  rank_score real not null default 0,
  fetched_at timestamptz not null default now(),
  indexed_at timestamptz not null default now(),
  search_vector tsvector generated always as (
    setweight(to_tsvector('simple', coalesce(title, '')), 'A') ||
    setweight(to_tsvector('simple', coalesce(description, '')), 'B') ||
    setweight(to_tsvector('simple', coalesce(content_text, '')), 'C') ||
    setweight(to_tsvector('simple', coalesce(domain, '')), 'B')
  ) stored
);

create index if not exists web_search_documents_fts_idx
  on public.web_search_documents using gin (search_vector);

create index if not exists web_search_documents_title_trgm_idx
  on public.web_search_documents using gin (title gin_trgm_ops);

create index if not exists web_search_documents_domain_trgm_idx
  on public.web_search_documents using gin (domain gin_trgm_ops);

create index if not exists web_search_documents_kind_idx
  on public.web_search_documents (kind, indexed_at desc);

create index if not exists web_search_documents_domain_idx
  on public.web_search_documents (domain, indexed_at desc);

create table if not exists public.web_crawl_queue (
  id bigint generated by default as identity primary key,
  url text not null unique,
  depth integer not null default 0,
  priority integer not null default 0,
  status text not null default 'pending'
    check (status in ('pending', 'processing', 'done', 'failed', 'blocked')),
  attempts integer not null default 0,
  next_attempt_at timestamptz not null default now(),
  last_error text,
  discovered_from text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists web_crawl_queue_pick_idx
  on public.web_crawl_queue (status, next_attempt_at, priority desc, id)
  where status in ('pending', 'failed');

create table if not exists public.search_cache (
  cache_key text primary key,
  results jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists search_cache_created_at_idx
  on public.search_cache (created_at);

alter table public.web_search_documents enable row level security;
alter table public.web_crawl_queue enable row level security;
alter table public.search_cache enable row level security;

drop policy if exists web_search_documents_public_read on public.web_search_documents;
create policy web_search_documents_public_read
  on public.web_search_documents
  for select
  using (true);

-- Queue/cache are intentionally service-role only. No public RLS policies.

create or replace function public.search_web_index(
  p_query text,
  p_category text default 'all',
  p_limit integer default 20,
  p_offset integer default 0,
  p_locale text default 'uz'
)
returns table (
  id uuid,
  type text,
  title text,
  snippet text,
  url text,
  display_url text,
  thumbnail_url text,
  source text,
  published_at timestamptz,
  author text,
  width integer,
  height integer,
  duration_seconds integer,
  score real
)
language sql
stable
security definer
set search_path = public
as $$
  with params as (
    select
      nullif(trim(coalesce(p_query, '')), '') as q,
      greatest(1, least(coalesce(p_limit, 20), 50)) as lim,
      greatest(0, coalesce(p_offset, 0)) as off,
      case
        when p_category in ('all','web','wikipedia','news','images','videos') then p_category
        else 'all'
      end as cat
  ),
  ranked as (
    select
      d.*,
      (
        5.0 * ts_rank_cd(d.search_vector, websearch_to_tsquery('simple', params.q)) +
        2.0 * similarity(lower(d.title), lower(params.q)) +
        0.8 * similarity(lower(d.domain), lower(params.q)) +
        coalesce(d.rank_score, 0) +
        case
          when d.published_at is not null and d.published_at > now() - interval '30 days' then 0.4
          when d.indexed_at > now() - interval '7 days' then 0.2
          else 0
        end
      )::real as computed_score
    from public.web_search_documents d
    cross join params
    where params.q is not null
      and (
        d.search_vector @@ websearch_to_tsquery('simple', params.q)
        or lower(d.title) % lower(params.q)
        or lower(d.domain) % lower(params.q)
      )
      and (
        params.cat = 'all'
        or (params.cat = 'images' and d.kind = 'image')
        or (params.cat = 'videos' and d.kind = 'video')
        or (params.cat = 'wikipedia' and d.kind = 'wikipedia')
        or (params.cat = 'news' and d.kind = 'news')
        or (params.cat = 'web' and d.kind in ('web','wikipedia','news'))
      )
      and (
        p_locale is null
        or p_locale = ''
        or d.language is null
        or d.language = p_locale
        or d.language = split_part(p_locale, '-', 1)
      )
  )
  select
    r.id,
    case
      when r.kind = 'image' then 'image'
      when r.kind = 'video' then 'video'
      else r.kind
    end as type,
    coalesce(nullif(r.title, ''), r.domain) as title,
    coalesce(
      nullif(r.description, ''),
      nullif(left(r.content_text, 420), ''),
      r.url
    ) as snippet,
    r.url,
    r.domain || case when r.path = '/' then '' else ' › ' || trim(both '/' from r.path) end as display_url,
    r.thumbnail_url,
    r.domain as source,
    r.published_at,
    r.author,
    r.width,
    r.height,
    r.duration_seconds,
    r.computed_score as score
  from ranked r
  cross join params
  order by r.computed_score desc, r.rank_score desc, r.indexed_at desc
  limit params.lim
  offset params.off;
$$;

revoke all on function public.search_web_index(text,text,integer,integer,text) from public;
grant execute on function public.search_web_index(text,text,integer,integer,text) to service_role;

create or replace function public.enqueue_web_url(
  p_url text,
  p_depth integer default 0,
  p_priority integer default 0,
  p_discovered_from text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_url is null or length(trim(p_url)) = 0 then
    return;
  end if;

  insert into public.web_crawl_queue (
    url, depth, priority, status, next_attempt_at, discovered_from, updated_at
  )
  values (
    trim(p_url),
    greatest(0, least(coalesce(p_depth, 0), 32)),
    coalesce(p_priority, 0),
    'pending',
    now(),
    p_discovered_from,
    now()
  )
  on conflict (url) do update
    set priority = greatest(public.web_crawl_queue.priority, excluded.priority),
        depth = least(public.web_crawl_queue.depth, excluded.depth),
        status = case
          when public.web_crawl_queue.status = 'blocked' then 'blocked'
          else 'pending'
        end,
        next_attempt_at = least(public.web_crawl_queue.next_attempt_at, now()),
        updated_at = now();
end;
$$;

revoke all on function public.enqueue_web_url(text,integer,integer,text) from public;
grant execute on function public.enqueue_web_url(text,integer,integer,text) to service_role;

-- Start from Alsamos itself. The crawler follows outbound links, so the graph
-- can grow without relying on another search engine's index.
select public.enqueue_web_url('https://www.alsamos.com/', 0, 100, null);
