-- DEPRECATED - DO NOT APPLY. This file intentionally does nothing.
--
-- This migration expected to own the premium map schema:
--   saved_places(place_key, collection, category, ...)
--   place_visits(...)
--   place_reviews(place_key, comment, rating)
--   taxi_providers(...)
--   track_place_visit(...), place_rating_summary(p_place_key)
--
-- Two of those tables already existed, with different column names:
--
--   saved_places, from 20260712200000_map_p0_features.sql
--     id, user_id, list_id -> saved_place_lists(id), name, latitude,
--     longitude, address, notes, icon, is_favorite, visited_at,
--     created_at, updated_at
--     No collection column. Grouping is done through list_id.
--
--   place_reviews, from 20260803020000_social_map_features.sql
--     id, user_id, place_id, place_name, rating, review_text, categories,
--     category_ratings, photo_urls, helpful_count, visit_date,
--     created_at, updated_at, UNIQUE(user_id, place_id)
--     No place_key, no comment.
--
-- This is the direct cause of the reported failure:
--   ERROR: 42703: column "collection" does not exist
-- CREATE TABLE IF NOT EXISTS did nothing because saved_places was already
-- there, so collection was never added, and the CREATE INDEX that followed
-- referenced a column that does not exist. Adding per-column ALTER statements
-- fixed the symptom but not the cause: the web client was still assuming it
-- owned tables it did not own.
--
-- Genuinely new, and therefore kept in the replacement migration:
--   place_visits    - passive dwell tracking, distinct from the deliberate,
--                     social check_ins table
--   taxi_providers  - external operators we deep-link into, distinct from
--                     taxi_live_locations, which tracks our own drivers
--
-- Replaced by:
--   alsamos-superapp/supabase/migrations/20260831053000_reconcile_map_schema.sql
--
-- That migration keeps the canonical tables authoritative and adds:
--   * saved_places.collection / category / place_key, with a trigger that
--     derives collection from the list name and place_key from coordinates
--   * place_reviews.place_key / comment, with a trigger that fills the NOT NULL
--     place_id and place_name so web inserts succeed
--   * place_rating_summary(p_place_key), reading the base table so it stays
--     live, unlike the place_statistics materialized view
--   * place_visits, taxi_providers, track_place_visit()
--   * products.latitude / longitude and products_geo_idx
--
-- See docs/CONTRACTS/db-schema.md section 4 for the full verified diff.

SELECT 1;
