-- Alsamos Search activity ledger
--
-- `search_history` is a recent-search UX list and intentionally de-duplicates
-- repeated queries. AI/personalization analytics need a different model: one
-- immutable activity row for every committed search. This table separates the
-- two concerns so "what do I search most?" is based on real frequency rather
-- than the recent-list representation.

create table if not exists public.search_activity_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  query text not null,
  normalized_query text not null,
  source text not null default 'search',
  searched_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  constraint search_activity_query_length check (char_length(query) between 2 and 240),
  constraint search_activity_normalized_length check (char_length(normalized_query) between 2 and 240),
  constraint search_activity_source_length check (char_length(source) between 1 and 40),
  constraint search_activity_metadata_object check (jsonb_typeof(metadata) = 'object')
);

create index if not exists search_activity_user_time_idx
  on public.search_activity_events (user_id, searched_at desc);
create index if not exists search_activity_user_normalized_time_idx
  on public.search_activity_events (user_id, normalized_query, searched_at desc);

alter table public.search_activity_events enable row level security;

revoke all on table public.search_activity_events from anon, authenticated;
grant select, delete on table public.search_activity_events to authenticated;

-- Users can inspect or erase only their own search activity. Normal inserts go
-- through the search_history trigger/RPC so user_id cannot be forged.
drop policy if exists search_activity_select_own on public.search_activity_events;
create policy search_activity_select_own
on public.search_activity_events
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists search_activity_delete_own on public.search_activity_events;
create policy search_activity_delete_own
on public.search_activity_events
for delete
to authenticated
using (auth.uid() = user_id);

create or replace function public.normalize_search_activity_query(p_query text)
returns text
language sql
immutable
strict
as $$
  select lower(regexp_replace(trim(p_query), '\s+', ' ', 'g'));
$$;

-- Every successful insert into the recent-search table records one real search
-- event before the recent list can de-duplicate/reorder itself on the next use.
create or replace function public.capture_search_history_activity()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_query text;
begin
  v_query := regexp_replace(trim(coalesce(new.query, '')), '\s+', ' ', 'g');
  if char_length(v_query) < 2 then
    return new;
  end if;

  insert into public.search_activity_events (
    user_id,
    query,
    normalized_query,
    source,
    metadata,
    searched_at
  ) values (
    new.user_id,
    left(v_query, 240),
    public.normalize_search_activity_query(left(v_query, 240)),
    'search_page',
    '{}'::jsonb,
    coalesce(new.created_at, now())
  );

  return new;
end;
$$;

drop trigger if exists search_history_capture_activity on public.search_history;
create trigger search_history_capture_activity
after insert on public.search_history
for each row
execute function public.capture_search_history_activity();

-- Existing recent rows represent at least one historical search each. Backfill
-- once without pretending we know repetition counts from before this migration.
insert into public.search_activity_events (
  user_id,
  query,
  normalized_query,
  source,
  metadata,
  searched_at
)
select
  sh.user_id,
  left(regexp_replace(trim(sh.query), '\s+', ' ', 'g'), 240),
  public.normalize_search_activity_query(left(regexp_replace(trim(sh.query), '\s+', ' ', 'g'), 240)),
  'search_history_backfill',
  jsonb_build_object('backfilled', true),
  sh.created_at
from public.search_history sh
where char_length(trim(sh.query)) >= 2
  and not exists (
    select 1
    from public.search_activity_events sae
    where sae.user_id = sh.user_id
      and sae.source = 'search_history_backfill'
      and sae.normalized_query = public.normalize_search_activity_query(left(regexp_replace(trim(sh.query), '\s+', ' ', 'g'), 240))
  );

-- Canonical privacy action. The frontend can migrate to this RPC instead of
-- issuing two unrelated DELETE requests. It clears both the visible recent
-- list and the private AI/search activity ledger atomically.
create or replace function public.clear_my_search_history()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_recent bigint := 0;
  v_events bigint := 0;
begin
  if v_user_id is null then
    raise exception 'auth_required';
  end if;

  delete from public.search_history where user_id = v_user_id;
  get diagnostics v_recent = row_count;

  delete from public.search_activity_events where user_id = v_user_id;
  get diagnostics v_events = row_count;

  return jsonb_build_object(
    'success', true,
    'recent_deleted', v_recent,
    'activity_deleted', v_events
  );
end;
$$;

grant execute on function public.clear_my_search_history() to authenticated;
revoke execute on function public.clear_my_search_history() from anon;

-- A bounded server-side summary avoids shipping thousands of private search
-- events to the browser/AI runtime. Service-role callers can still query the
-- table directly, but authenticated clients can request only their own result.
create or replace function public.my_search_insights_v2(
  p_days integer default 30,
  p_query_contains text default null,
  p_limit integer default 10
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_days integer := greatest(1, least(coalesce(p_days, 30), 730));
  v_limit integer := greatest(1, least(coalesce(p_limit, 10), 30));
  v_contains text := nullif(trim(coalesce(p_query_contains, '')), '');
  v_since timestamptz;
  v_total bigint;
  v_unique bigint;
  v_top jsonb;
  v_recent jsonb;
begin
  if v_user_id is null then
    raise exception 'auth_required';
  end if;

  v_since := now() - make_interval(days => v_days);

  select count(*), count(distinct normalized_query)
  into v_total, v_unique
  from public.search_activity_events
  where user_id = v_user_id
    and searched_at >= v_since
    and (v_contains is null or query ilike '%' || v_contains || '%');

  select coalesce(jsonb_agg(to_jsonb(row_data) order by row_data.search_count desc, row_data.last_searched_at desc), '[]'::jsonb)
  into v_top
  from (
    select
      max(query) as query,
      normalized_query,
      count(*)::bigint as search_count,
      max(searched_at) as last_searched_at
    from public.search_activity_events
    where user_id = v_user_id
      and searched_at >= v_since
      and (v_contains is null or query ilike '%' || v_contains || '%')
    group by normalized_query
    order by count(*) desc, max(searched_at) desc
    limit v_limit
  ) row_data;

  select coalesce(jsonb_agg(to_jsonb(row_data) order by row_data.searched_at desc), '[]'::jsonb)
  into v_recent
  from (
    select query, searched_at
    from public.search_activity_events
    where user_id = v_user_id
      and searched_at >= v_since
      and (v_contains is null or query ilike '%' || v_contains || '%')
    order by searched_at desc
    limit v_limit
  ) row_data;

  return jsonb_build_object(
    'days', v_days,
    'total_searches', coalesce(v_total, 0),
    'unique_queries', coalesce(v_unique, 0),
    'top', v_top,
    'recent', v_recent,
    'source', 'search_activity_events'
  );
end;
$$;

grant execute on function public.my_search_insights_v2(integer, text, integer) to authenticated;
revoke execute on function public.my_search_insights_v2(integer, text, integer) from anon;
