-- Shared rotating Gemini key pool for Alsamos AI + AI Search.
--
-- IMPORTANT: never commit real API keys in migrations. Production credentials
-- are inserted only through a secure server-side/admin channel.

create table if not exists public.ai_api_key_pool (
  id bigint generated by default as identity primary key,
  api_key text not null unique,
  is_active boolean not null default true,
  priority integer not null default 100,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.ai_api_key_pool enable row level security;

revoke all on table public.ai_api_key_pool from anon;
revoke all on table public.ai_api_key_pool from authenticated;
grant select on table public.ai_api_key_pool to service_role;

comment on table public.ai_api_key_pool is
  'Server-only rotating Google Gemini key pool shared by Alsamos AI and AI Search.';
comment on column public.ai_api_key_pool.api_key is
  'Sensitive server-side credential. Never expose to clients.';
