-- Privacy-preserving contact discovery for Alsamos.
--
-- The browser sends SHA-256 hashes of normalized phone/email values. Raw device
-- contacts are never stored in Alsamos. The SECURITY DEFINER function compares
-- those hashes against auth.users server-side and returns public profile fields
-- only. Successful matches may be persisted as user-to-user suggestion edges;
-- no phone, email or hash is persisted in that edge table.

create extension if not exists pgcrypto with schema extensions;

create table if not exists public.contact_discovery_matches (
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  matched_user_id uuid not null references auth.users(id) on delete cascade,
  source text not null default 'device_contact' check (source in ('device_contact')),
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  primary key (owner_user_id, matched_user_id),
  check (owner_user_id <> matched_user_id)
);

create index if not exists contact_discovery_matches_owner_seen_idx
  on public.contact_discovery_matches (owner_user_id, last_seen_at desc);

alter table public.contact_discovery_matches enable row level security;
revoke all on table public.contact_discovery_matches from anon, authenticated;
grant select, delete on table public.contact_discovery_matches to authenticated;

drop policy if exists contact_discovery_matches_select_own on public.contact_discovery_matches;
create policy contact_discovery_matches_select_own
on public.contact_discovery_matches
for select
to authenticated
using (auth.uid() = owner_user_id);

drop policy if exists contact_discovery_matches_delete_own on public.contact_discovery_matches;
create policy contact_discovery_matches_delete_own
on public.contact_discovery_matches
for delete
to authenticated
using (auth.uid() = owner_user_id);

create table if not exists public.contact_discovery_rate_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  requested_count integer not null check (requested_count >= 0),
  matched_count integer not null default 0 check (matched_count >= 0),
  created_at timestamptz not null default now()
);

create index if not exists contact_discovery_rate_events_user_created_idx
  on public.contact_discovery_rate_events (user_id, created_at desc);

alter table public.contact_discovery_rate_events enable row level security;
revoke all on table public.contact_discovery_rate_events from anon, authenticated;

create or replace function public.sync_my_contact_hashes(
  p_phone_hashes text[] default '{}'::text[],
  p_email_hashes text[] default '{}'::text[]
)
returns table (
  user_id uuid,
  username text,
  display_name text,
  avatar_url text,
  matched_by text,
  is_following boolean,
  mutual_count bigint
)
language plpgsql
security definer
set search_path = public, auth, extensions
as $$
declare
  v_user_id uuid := auth.uid();
  v_phone_hashes text[];
  v_email_hashes text[];
  v_requested_count integer;
  v_recent_calls integer;
  v_match_count integer := 0;
begin
  if v_user_id is null then
    raise exception 'auth_required';
  end if;

  -- Keep only canonical SHA-256 hex strings, dedupe them and cap each batch.
  select coalesce(array_agg(value order by value), '{}'::text[])
  into v_phone_hashes
  from (
    select distinct lower(trim(value)) as value
    from unnest(coalesce(p_phone_hashes, '{}'::text[])) as value
    where lower(trim(value)) ~ '^[0-9a-f]{64}$'
    limit 500
  ) clean;

  select coalesce(array_agg(value order by value), '{}'::text[])
  into v_email_hashes
  from (
    select distinct lower(trim(value)) as value
    from unnest(coalesce(p_email_hashes, '{}'::text[])) as value
    where lower(trim(value)) ~ '^[0-9a-f]{64}$'
    limit 500
  ) clean;

  v_requested_count := coalesce(cardinality(v_phone_hashes), 0) + coalesce(cardinality(v_email_hashes), 0);
  if v_requested_count = 0 then
    return;
  end if;

  if v_requested_count > 750 then
    raise exception 'contact_batch_too_large';
  end if;

  select count(*)::integer
  into v_recent_calls
  from public.contact_discovery_rate_events
  where user_id = v_user_id
    and created_at > now() - interval '1 minute';

  if v_recent_calls >= 8 then
    raise exception 'contact_discovery_rate_limited';
  end if;

  create temporary table if not exists pg_temp.alsamos_contact_matches (
    matched_user_id uuid primary key,
    matched_by text not null
  ) on commit drop;
  truncate pg_temp.alsamos_contact_matches;

  insert into pg_temp.alsamos_contact_matches (matched_user_id, matched_by)
  select
    u.id,
    case
      when cardinality(v_phone_hashes) > 0
        and encode(extensions.digest(regexp_replace(coalesce(u.phone, ''), '[^0-9]+', '', 'g'), 'sha256'), 'hex') = any(v_phone_hashes)
      then 'phone'
      else 'email'
    end
  from auth.users u
  where u.id <> v_user_id
    and (
      (
        coalesce(u.phone, '') <> ''
        and length(regexp_replace(u.phone, '[^0-9]+', '', 'g')) >= 7
        and encode(extensions.digest(regexp_replace(u.phone, '[^0-9]+', '', 'g'), 'sha256'), 'hex') = any(v_phone_hashes)
      )
      or
      (
        coalesce(u.email, '') <> ''
        and encode(extensions.digest(lower(trim(u.email)), 'sha256'), 'hex') = any(v_email_hashes)
      )
    )
    -- Respect blocks in either direction. Contact discovery must not become a
    -- side channel for finding a blocked account.
    and not exists (
      select 1
      from public.blocked_users b
      where (b.blocker_id = v_user_id and b.blocked_id = u.id)
         or (b.blocker_id = u.id and b.blocked_id = v_user_id)
    )
  on conflict (matched_user_id) do update
    set matched_by = excluded.matched_by;

  select count(*)::integer into v_match_count from pg_temp.alsamos_contact_matches;

  insert into public.contact_discovery_matches (owner_user_id, matched_user_id, source, last_seen_at)
  select v_user_id, m.matched_user_id, 'device_contact', now()
  from pg_temp.alsamos_contact_matches m
  on conflict (owner_user_id, matched_user_id)
  do update set last_seen_at = excluded.last_seen_at;

  insert into public.contact_discovery_rate_events (user_id, requested_count, matched_count)
  values (v_user_id, v_requested_count, v_match_count);

  return query
  select
    p.id as user_id,
    p.username,
    p.display_name,
    p.avatar_url,
    m.matched_by,
    exists (
      select 1 from public.follows f
      where f.follower_id = v_user_id and f.following_id = p.id
    ) as is_following,
    (
      select count(*)
      from public.follows mine
      join public.follows theirs on theirs.following_id = mine.following_id
      where mine.follower_id = v_user_id
        and theirs.follower_id = p.id
        and mine.following_id not in (v_user_id, p.id)
    ) as mutual_count
  from pg_temp.alsamos_contact_matches m
  join public.profiles p on p.id = m.matched_user_id
  order by
    exists (
      select 1 from public.follows f
      where f.follower_id = v_user_id and f.following_id = p.id
    ) desc,
    mutual_count desc,
    coalesce(p.display_name, p.username, '') asc;
end;
$$;

create or replace function public.my_contact_suggestions(p_limit integer default 20)
returns table (
  user_id uuid,
  username text,
  display_name text,
  avatar_url text,
  is_following boolean,
  mutual_count bigint,
  last_seen_at timestamptz
)
language sql
security definer
set search_path = public
stable
as $$
  select
    p.id,
    p.username,
    p.display_name,
    p.avatar_url,
    exists (
      select 1 from public.follows f
      where f.follower_id = auth.uid() and f.following_id = p.id
    ) as is_following,
    (
      select count(*)
      from public.follows mine
      join public.follows theirs on theirs.following_id = mine.following_id
      where mine.follower_id = auth.uid()
        and theirs.follower_id = p.id
        and mine.following_id not in (auth.uid(), p.id)
    ) as mutual_count,
    m.last_seen_at
  from public.contact_discovery_matches m
  join public.profiles p on p.id = m.matched_user_id
  where auth.uid() is not null
    and m.owner_user_id = auth.uid()
    and not exists (
      select 1 from public.blocked_users b
      where (b.blocker_id = auth.uid() and b.blocked_id = p.id)
         or (b.blocker_id = p.id and b.blocked_id = auth.uid())
    )
  order by is_following desc, mutual_count desc, m.last_seen_at desc
  limit least(greatest(coalesce(p_limit, 20), 1), 100);
$$;

grant execute on function public.sync_my_contact_hashes(text[], text[]) to authenticated;
grant execute on function public.my_contact_suggestions(integer) to authenticated;
revoke execute on function public.sync_my_contact_hashes(text[], text[]) from anon;
revoke execute on function public.my_contact_suggestions(integer) from anon;

comment on function public.sync_my_contact_hashes(text[], text[]) is
  'Matches client-side SHA-256 contact hashes to auth users and returns public profiles only; stores no raw contact values or hashes.';
comment on table public.contact_discovery_matches is
  'Private per-user suggestion edges derived from explicit contact discovery. Contains user IDs only, never raw contact data or hashes.';
