-- DEPRECATED - DO NOT APPLY. This file intentionally does nothing.
--
-- This migration originally created its own sticker schema:
--   sticker_packs(slug, author_id, is_public, sticker_count, install_count, ...)
--   stickers(file_url, thumb_url, width, height, ...)
--   sticker_pack_installs(user_id, pack_id, position, installed_at)
--   sticker_usage(user_id, file_url, kind, use_count, last_used_at)
--   touch_sticker_usage(p_file_url, p_kind, p_sticker_id)
--
-- That was a mistake. Those tables already existed, created by
--   alsamos-superapp/supabase/migrations/20260716000000_telegram_stickers.sql
-- with different column names:
--   sticker_packs(title, cover_url, cover_lottie_url, created_by, is_animated)
--   stickers(emoji, image_url, lottie_url, video_url, thumbnail_url, type, position)
--   user_sticker_packs(user_id, pack_id, updated_at)
--   recent_stickers(user_id, sticker_id, use_count, last_used)
--
-- Running the original version of this file aborts with:
--   ERROR: 42703: column "is_public" does not exist
--
-- The reason is the same failure mode that produced the earlier
--   ERROR: 42703: column "collection" does not exist
-- CREATE TABLE IF NOT EXISTS silently does nothing when the table is already
-- there, so none of the new columns get created, and the policies and indexes
-- that follow then reference columns that do not exist.
--
-- Replaced by:
--   alsamos-superapp/supabase/migrations/20260831052300_reconcile_sticker_schema.sql
--
-- That migration keeps the canonical tables authoritative and only adds what
-- the web client is missing:
--   * sticker_packs.slug / is_public / sticker_count / install_count
--   * stickers.file_url / thumb_url / width / height, backfilled from
--     image_url / video_url / lottie_url / thumbnail_url
--   * a trigger keeping both column namings in sync in either direction
--   * a default on stickers.type, which is NOT NULL with no default
--   * user_sticker_packs.position, so the install table stays single
--   * sticker_usage, the one genuinely new table, because recent_stickers
--     cannot hold GIFs (its sticker_id is a required foreign key)
--
-- Web client changes still required, tracked in docs/CONTRACTS/db-schema.md:
--   * read stickers via file_url (now backfilled) or image_url
--   * stop writing sticker_pack_installs, use user_sticker_packs
--
-- See also docs/CONTRACTS/db-schema.md section 1 for migration ownership:
-- new migrations are authored in alsamos-superapp/supabase/migrations/.

SELECT 1;
